# Generated by ariadne-codegen
# Source: graphql

from typing import List

from .base_model import BaseModel
from .fragments import Source


class GetWorkspaceSources(BaseModel):
    sources: List["GetWorkspaceSourcesSources"]


class GetWorkspaceSourcesSources(Source):
    pass
