# Generated by ariadne-codegen
# Source: graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import Chat


class GetChat(BaseModel):
    chats_by_pk: Optional["GetChatChatsByPk"]


class GetChatChatsByPk(Chat):
    pass
