# Generated by ariadne-codegen
# Source: graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import Source


class GetSource(BaseModel):
    sources_by_pk: Optional["GetSourceSourcesByPk"]


class GetSourceSourcesByPk(Source):
    pass
