# Generated by ariadne-codegen
# Source: graphql

from typing import List

from .base_model import BaseModel
from .fragments import Chat


class GetChats(BaseModel):
    chats: List["GetChatsChats"]


class GetChatsChats(Chat):
    pass
