# Generated by ariadne-codegen
# Source: graphql

from typing import List

from .base_model import BaseModel
from .fragments import Workspace


class GetWorkspaces(BaseModel):
    workspaces: List["GetWorkspacesWorkspaces"]


class GetWorkspacesWorkspaces(Workspace):
    pass
