# Generated by ariadne-codegen
# Source: graphql

from typing import List

from .base_model import BaseModel
from .fragments import CrmRecord


class GetChatCrmRecords(BaseModel):
    crm_records: List["GetChatCrmRecordsCrmRecords"]


class GetChatCrmRecordsCrmRecords(CrmRecord):
    pass
