# Generated by ariadne-codegen
# Source: graphql

from typing import List

from .base_model import BaseModel
from .fragments import Connection


class GetWorkspaceConnections(BaseModel):
    connections: List["GetWorkspaceConnectionsConnections"]


class GetWorkspaceConnectionsConnections(Connection):
    pass
