# Generated by ariadne-codegen
# Source: graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import User


class GetUser(BaseModel):
    user: Optional["GetUserUser"]


class GetUserUser(User):
    pass
