# Generated by ariadne-codegen
# Source: graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import Workspace


class GetWorkspace(BaseModel):
    workspaces_by_pk: Optional["GetWorkspaceWorkspacesByPk"]


class GetWorkspaceWorkspacesByPk(Workspace):
    pass
