# Generated by ariadne-codegen
# Source: graphql

from typing import Any

from pydantic import Field

from .base_model import BaseModel


class SignOut(BaseModel):
    sign_out: Any = Field(alias="signOut")
